RESULT = molecule
SOURCES =	source/atoms/atom.ml \
			source/atoms/hydrogen.ml \
			source/atoms/carbon.ml \
			source/atoms/oxygen.ml \
			source/atoms/titanium.ml \
			source/atoms/iron.ml \
			source/atoms/gold.ml \
			source/atoms/thulium.ml \
			\
			source/molecules/molecule.ml \
			source/molecules/water.ml \
			source/molecules/methane.ml \
			source/molecules/carbon_dioxyde.ml \
			source/molecules/iron_oxide.ml \
			source/molecules/hexapentaenylidene.ml \
			\
			main.ml \

include OCamlMakefile
