RESULT = atoms
SOURCES =	source/atom.ml \
			source/hydrogen.ml \
			source/carbon.ml \
			source/oxygen.ml \
			source/titanium.ml \
			source/iron.ml \
			source/gold.ml \
			source/thulium.ml \
			main.ml \

include OCamlMakefile
