RESULT = alkane
SOURCES =	source/atoms/atom.ml \
			source/atoms/hydrogen.ml \
			source/atoms/carbon.ml \
			\
			source/molecules/molecule.ml \
			source/molecules/alkane.ml \
			source/molecules/methane.ml \
			source/molecules/ethane.ml \
			source/molecules/octane.ml \
			\
			main.ml \

include OCamlMakefile
